# Ejemplos

POST http://localhost:3000/api/productos HTTP/1.1
content-type: application/json

{ 
    "nombre": "Eva", 
    "precio": 20 
}

### 

POST http://localhost:3000/api/productos HTTP/1.1
content-type: application/json

{ 
    "nombre": "fresa", 
    "precio": 21 
}

### 

GET http://localhost:3000/api/productos HTTP/1.1
content-type: application/json

###

GET http://localhost:3000/api/productos/65539ff7e3ffa13cd784f3cb HTTP/1.1
content-type: application/json

###

PUT http://localhost:3000/api/productos/6566230a226050da60b41159 HTTP/1.1
content-type: application/json

{ 
    "nombre": "fresa", 
    "precio": 8
}

###

DELETE http://localhost:3000/api/productos/656622fc226050da60b41158 HTTP/1.1
content-type: application/json

###

DELETE https://nxapi-mongodb.vercel.app/api/productos/6542da20c20d9ad95c739701 HTTP/1.1
content-type: application/json

### 

POST https://nxapi-mongodb.vercel.app/api/productos HTTP/1.1
content-type: application/json

{ 
    "nombre": "pera", 
    "precio": 21 
}

### 

DELETE https://nxapi-mongodb.vercel.app/api/productos/6542da35c20d9ad95c739702
content-type: application/json
